[project]
name = "matrix"
version = "0.1.0"
description = "Enter the Matrix - an introduction to Linear Algebra (vectors, matrices, ...)"
readme = "README.md"
authors = [
    { name = "tristan-gscn", email = "trgascoi@student.42lyon.fr" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
matrix = "matrix:main"

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "src"
module-name = "matrix._core"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]
