from collections.abc import Iterator
from typing import Self

class Vector:
    # core
    def __init__(self, data: list[float]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

    # ex00
    def copy(self) -> Self: ...
    def __add__(self, other: "Vector") -> "Vector": ...
    def __sub__(self, other: "Vector") -> "Vector": ...
    def scl(self, a: float) -> None: ...

class Matrix:
    # core
    def __init__(self, rows: list[list[float]]) -> None: ...
    def copy(self) -> Self: ...
    def shape(self) -> tuple[int, int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

    # ex00
    def __add__(self, other: "Matrix") -> "Matrix": ...
    def __sub__(self, other: "Matrix") -> "Matrix": ...
    def scl(self, a: float) -> None: ...
