from collections.abc import Iterator
from typing import Self

class Vector:
    # core
    def __init__(self, data: list[float]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

    # ex00
    def copy(self) -> Self: ...
    def add(self, v: "Vector") -> None: ...
    def sub(self, v: "Vector") -> None: ...
    def scl(self, a: float) -> None: ...

class Matrix:
    # core
    def __init__(self, rows: list[list[float]]) -> None: ...
    def copy(self) -> Self: ...
    def shape(self) -> tuple[int, int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

    # ex00
    def add(self, v: "Matrix") -> None: ...
    def sub(self, v: "Matrix") -> None: ...
    def scl(self, a: float) -> None: ...
